import 'package:flutter/widgets.dart';
import 'package:mova/services/language_controller.dart';

class MovaLocalizations {
  const MovaLocalizations(this.locale);

  final Locale locale;

  static const delegate = _MovaLocalizationsDelegate();

  static const _values = <String, Map<String, String>>{
    'es': {
      'home': 'Inicio',
      'preparing_finances': 'Preparando tu espacio financiero',
      'my_profile': 'Mi perfil',
      'my_account': 'Mi cuenta',
      'analysis': 'Análisis',
      'goals': 'Metas',
      'more': 'Más',
      'today': 'Hoy',
      'this_week': 'Esta semana',
      'previous_week': 'Semana anterior',
      'this_month': 'Este mes',
      'previous_month': 'Mes anterior',
      'this_year': 'Este año',
      'previous_year': 'Año anterior',
      'analysis_subtitle': 'Conoce el comportamiento de tus finanzas',
      'home_summary': 'Este es tu resumen financiero',
      'hello': 'Hola',
      'daily_activity': 'Actividad diaria',
      'splash_tagline': 'Tu dinero, en movimiento.',
      'splash_motto': 'CONTROL • CLARIDAD • TRANQUILIDAD',
      'security_intro': 'Elige una sola forma de proteger tu sesión',
      'security_exclusive_note': 'Solo una opción puede estar activa. Al elegir otra, la protección anterior se reemplaza.',
      'expenses_by_category': 'Gastos por categoría',
      'no_period_expenses': 'Aún no hay gastos registrados en este periodo.',
      'record_movements_recommendations':
          'Registra movimientos para obtener recomendaciones.',
      'income': 'Ingresos',
      'expenses': 'Gastos',
      'balance': 'Balance',
      'period_summary': 'Resumen del periodo',
      'no_period_movements': 'No hay movimientos en este periodo.',
      'login_access': 'ACCESO PERSONAL',
      'welcome_back': 'Bienvenido de nuevo',
      'continue_finances': 'Continúa organizando tus finanzas.',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'remember_me': 'Recuérdame',
      'login': 'Iniciar sesión',
      'create_account': 'Crear cuenta',
      'forgot_password': '¿Olvidaste tu contraseña?',
      'no_account': '¿Aún no tienes una cuenta? ',
      'incorrect_data': 'Datos incorrectos',
      'missing_data': 'Faltan datos',
      'complete_fields': 'Completa todos los campos.',
      'personal_budget': 'Presupuesto',
      'notifications': 'Notificaciones',
      'security': 'Seguridad',
      'language': 'Idioma',
      'categories': 'Categorías',
      'shopping_lists': 'Listas de compras',
      'terms': 'Términos y condiciones',
      'privacy': 'Aviso de privacidad',
      'settings': 'Configuración',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'done': 'Listo',
      'select_language': 'Selecciona un idioma',
      'spanish': 'Español',
      'english': 'Inglés',
      'portuguese': 'Portugués',
      'english_native': 'English',
      'portuguese_native': 'Português',
      'spanish_native': 'Español',
      'unlock_mova': 'Desbloquear MOVA',
      'enter_pin': 'Ingresa tu PIN',
      'incorrect_pin': 'PIN incorrecto',
      'incorrect_pin_message': 'El PIN ingresado no es correcto.',
      'loading_section': 'Cargando tu sección',
      'movements': 'Movimientos',
      'financial_activity': 'Tu actividad financiera, en un solo lugar.',
      'all': 'Todos',
      'savings': 'Ahorro',
      'no_movements_filter': 'No hay movimientos en este filtro.',
      'add_income': 'Agregar ingreso',
      'add_expense': 'Agregar gasto',
      'income_help': 'Registra el dinero que recibiste',
      'expense_help': 'Registra en qué utilizaste tu dinero',
      'expense': 'Gasto',
      'income_singular': 'Ingreso',
      'how_much_received': '¿Cuánto recibiste?',
      'how_much': '¿Cuánto?',
      'what_spent': '¿En qué gastaste?',
      'income_source': 'Fuente del ingreso',
      'category': 'Categoría',
      'optional_note': 'Agregar nota (opcional)',
      'save_income': 'Guardar ingreso',
      'save_movement': 'Guardar movimiento',
      'create_your_account': 'Crea tu cuenta',
      'take_control': 'Empieza a tomar el control de tus finanzas.',
      'name': 'Nombre',
      'enter_name': 'Ingresa tu nombre',
      'enter_email': 'Ingresa tu correo',
      'create_password': 'Crea una contraseña',
      'repeat_password': 'Repite tu contraseña',
      'my_goals': 'Mis metas',
      'goals_subtitle': 'Convierte tus planes en objetivos',
      'new_goal': 'Nueva meta',
      'free_savings': 'Ahorro libre',
      'free_savings_help': 'Ahorra sin tener una meta específica',
      'no_goals_yet': 'Aún no tienes metas',
      'create_goal_savings':
          'Crea una meta para darle un objetivo a tus ahorros.',
      'no_goals_home': 'Aún no tienes metas. Crea una para empezar a ahorrar con un objetivo.',
      'add': 'Agregar',
      'withdraw': 'Retirar',
      'amount': 'Cantidad',
      'close': 'Cerrar',
      'my_shopping': 'Mis compras',
      'current': 'Actuales',
      'history': 'Historial',
      'new_list': 'Nueva lista',
      'no_completed_shopping': 'Aún no hay compras finalizadas',
      'plan_first_shopping': 'Planea tu primera compra',
      'create_list': 'Crear lista',
      'understood': 'Entendido',
      'something_wrong': 'Algo salió mal',
      'ready': 'Listo',
      'finance': 'FINANZAS',
      'your_money': 'Tu dinero.\nTus metas.\nTu control.',
      'welcome_subtitle': 'Organiza, ahorra y avanza con claridad.',
      'already_account': 'Ya tengo una cuenta',
      'protected_data': 'Tus datos están protegidos',
      'logout': 'Cerrar sesión',
      'close_session': '¿Quieres cerrar tu sesión?',
      'notifications_active': 'Notificaciones activas',
      'savings_goals': 'Metas de ahorro',
      'shopping': 'Compras',
      'view_all': 'Ver todos',
      'no_summary': 'No se pudo cargar el resumen',
      'recover_access': 'Recupera tu acceso',
      'new_password': 'Nueva contraseña',
      'confirm_password': 'Confirmar contraseña',
      'update': 'Actualizar',
      'saving': 'Guardando...',
      'verify': 'Verificar',
      'cancelled': 'Cancelado',
      'account_options': 'Opciones de cuenta',
      'preferences': 'Preferencias y opciones de MOVA',
      'exit_device': 'Salir de tu cuenta en este dispositivo',
      'choose_notifications': 'Elige qué avisos quieres recibir en MOVA.',
      'allow_notifications': 'Permitir notificaciones',
      'notifications_help': 'Activa o pausa todos los avisos de MOVA',
      'notification_types': 'TIPOS DE AVISO',
      'budget_help': 'Avisos relacionados con tu presupuesto',
      'goals_help': 'Recordatorios para avanzar en tus objetivos',
      'shopping_help': 'Recordatorios de listas pendientes',
      'Sal de tu cuenta en este dispositivo':
          'Sal de tu cuenta en este dispositivo',
      'Aún no tienes metas. Crea una para empezar a ahorrar con un objetivo.': 'Aún no tienes metas. Crea una para empezar a ahorrar con un objetivo.',
      'Crea una meta para darle un objetivo a tus ahorros.':
          'Crea una meta para darle un objetivo a tus ahorros.',
      'Gastos por categoría': 'Gastos por categoría',
      'Aún no hay gastos registrados en este periodo.':
          'Aún no hay gastos registrados en este periodo.',
      'Registra movimientos para obtener recomendaciones.':
          'Registra movimientos para obtener recomendaciones.',
    },
    'en': {
      'home': 'Home',
      'preparing_finances': 'Preparing your financial space',
      'showing_current_period': 'showing the current period',
      'my_profile': 'My profile',
      'my_account': 'My account',
      'analysis': 'Analytics',
      'goals': 'Goals',
      'more': 'More',
      'today': 'Today',
      'this_week': 'This week',
      'previous_week': 'Previous week',
      'this_month': 'This month',
      'previous_month': 'Previous month',
      'this_year': 'This year',
      'previous_year': 'Previous year',
      'analysis_subtitle': 'Understand your financial behavior',
      'home_summary': 'Here is your financial summary',
      'hello': 'Hello',
      'daily_activity': 'Daily activity',
      'splash_tagline': 'Your money, in motion.',
      'splash_motto': 'CONTROL • CLARITY • PEACE OF MIND',
      'security_intro': 'Choose one way to protect your session',
      'security_exclusive_note': 'Only one option can be active. Choosing another replaces the previous protection.',
      'expenses_by_category': 'Expenses by category',
      'no_period_expenses': 'There are no expenses recorded in this period.',
      'record_movements_recommendations':
          'Record movements to get recommendations.',
      'income': 'Income',
      'expenses': 'Expenses',
      'balance': 'Balance',
      'period_summary': 'Period summary',
      'no_period_movements': 'There are no movements in this period.',
      'login_access': 'PERSONAL ACCESS',
      'welcome_back': 'Welcome back',
      'continue_finances': 'Keep organizing your finances.',
      'email': 'Email',
      'password': 'Password',
      'remember_me': 'Remember me',
      'login': 'Log in',
      'create_account': 'Create account',
      'forgot_password': 'Forgot your password?',
      'no_account': "Don't have an account? ",
      'incorrect_data': 'Incorrect data',
      'missing_data': 'Missing data',
      'complete_fields': 'Complete all fields.',
      'personal_budget': 'Budget',
      'notifications': 'Notifications',
      'security': 'Security',
      'language': 'Language',
      'categories': 'Categories',
      'shopping_lists': 'Shopping lists',
      'terms': 'Terms and conditions',
      'privacy': 'Privacy notice',
      'settings': 'Settings',
      'save': 'Save',
      'cancel': 'Cancel',
      'done': 'Done',
      'select_language': 'Select a language',
      'spanish': 'Spanish',
      'english': 'English',
      'portuguese': 'Portuguese',
      'english_native': 'English',
      'portuguese_native': 'Português',
      'spanish_native': 'Español',
      'unlock_mova': 'Unlock MOVA',
      'enter_pin': 'Enter your PIN',
      'incorrect_pin': 'Incorrect PIN',
      'incorrect_pin_message': 'The PIN entered is incorrect.',
      'loading_section': 'Loading your section',
      'movements': 'Movements',
      'financial_activity': 'Your financial activity, all in one place.',
      'all': 'All',
      'savings': 'Savings',
      'no_movements_filter': 'There are no movements for this filter.',
      'add_income': 'Add income',
      'add_expense': 'Add expense',
      'income_help': 'Record money you received',
      'expense_help': 'Record how you used your money',
      'expense': 'Expense',
      'income_singular': 'Income',
      'how_much_received': 'How much did you receive?',
      'how_much': 'How much?',
      'what_spent': 'What did you spend it on?',
      'income_source': 'Income source',
      'category': 'Category',
      'optional_note': 'Add note (optional)',
      'save_income': 'Save income',
      'save_movement': 'Save movement',
      'create_your_account': 'Create your account',
      'take_control': 'Start taking control of your finances.',
      'name': 'Name',
      'enter_name': 'Enter your name',
      'enter_email': 'Enter your email',
      'create_password': 'Create a password',
      'repeat_password': 'Repeat your password',
      'my_goals': 'My goals',
      'goals_subtitle': 'Turn your plans into goals',
      'new_goal': 'New goal',
      'free_savings': 'Free savings',
      'free_savings_help': 'Save without a specific goal',
      'no_goals_yet': 'You have no goals yet',
      'create_goal_savings': 'Create a goal to give your savings a purpose.',
      'no_goals_home':
          'You have no goals yet. Create one to start saving toward a goal.',
      'add': 'Add',
      'withdraw': 'Withdraw',
      'amount': 'Amount',
      'close': 'Close',
      'my_shopping': 'My shopping',
      'current': 'Current',
      'history': 'History',
      'new_list': 'New list',
      'no_completed_shopping': 'No completed purchases yet',
      'plan_first_shopping': 'Plan your first purchase',
      'create_list': 'Create list',
      'understood': 'Got it',
      'something_wrong': 'Something went wrong',
      'ready': 'Done',
      'finance': 'FINANCE',
      'your_money': 'Your money.\nYour goals.\nYour control.',
      'welcome_subtitle': 'Organize, save, and move forward with clarity.',
      'already_account': 'I already have an account',
      'protected_data': 'Your data is protected',
      'logout': 'Log out',
      'close_session': 'Do you want to log out?',
      'notifications_active': 'Notifications enabled',
      'savings_goals': 'Savings goals',
      'shopping': 'Shopping',
      'view_all': 'View all',
      'no_summary': 'Could not load the summary',
      'recover_access': 'Recover your access',
      'new_password': 'New password',
      'confirm_password': 'Confirm password',
      'update': 'Update',
      'saving': 'Saving...',
      'verify': 'Verify',
      'cancelled': 'Cancelled',
      'account_options': 'Account options',
      'preferences': 'MOVA preferences and options',
      'exit_device': 'Sign out of this device',
      'choose_notifications':
          'Choose which notifications you want to receive in MOVA.',
      'allow_notifications': 'Allow notifications',
      'notifications_help': 'Turn all MOVA alerts on or off',
      'notification_types': 'NOTIFICATION TYPES',
      'budget_help': 'Alerts related to your budget',
      'goals_help': 'Reminders to advance your goals',
      'shopping_help': 'Reminders for pending lists',
      'Sal de tu cuenta en este dispositivo':
          'Sign out of your account on this device',
      'Aún no tienes metas. Crea una para empezar a ahorrar con un objetivo.':
          'You have no goals yet. Create one to start saving toward a goal.',
      'Crea una meta para darle un objetivo a tus ahorros.':
          'Create a goal to give your savings a purpose.',
      'Gastos por categoría': 'Expenses by category',
      'Aún no hay gastos registrados en este periodo.':
          'There are no expenses recorded in this period.',
      'Registra movimientos para obtener recomendaciones.':
          'Record movements to get recommendations.',
    },
    'pt': {
      'home': 'Início',
      'preparing_finances': 'Preparando seu espaço financeiro',
      'showing_current_period': 'mostrando o período atual',
      'my_profile': 'Meu perfil',
      'my_account': 'Minha conta',
      'analysis': 'Análise',
      'goals': 'Metas',
      'more': 'Mais',
      'today': 'Hoje',
      'this_week': 'Esta semana',
      'previous_week': 'Semana anterior',
      'this_month': 'Este mês',
      'previous_month': 'Mês anterior',
      'this_year': 'Este ano',
      'previous_year': 'Ano anterior',
      'analysis_subtitle': 'Conheça o comportamento das suas finanças',
      'home_summary': 'Este é o seu resumo financeiro',
      'hello': 'Olá',
      'daily_activity': 'Atividade diária',
      'splash_tagline': 'Seu dinheiro em movimento.',
      'splash_motto': 'CONTROLE • CLAREZA • TRANQUILIDADE',
      'security_intro': 'Escolha uma forma de proteger sua sessão',
      'security_exclusive_note': 'Somente uma opção pode estar ativa. Escolher outra substitui a proteção anterior.',
      'expenses_by_category': 'Despesas por categoria',
      'no_period_expenses': 'Ainda não há despesas registradas neste período.',
      'record_movements_recommendations':
          'Registre movimentações para obter recomendações.',
      'income': 'Receitas',
      'expenses': 'Despesas',
      'balance': 'Saldo',
      'period_summary': 'Resumo do período',
      'no_period_movements': 'Não há movimentações neste período.',
      'login_access': 'ACESSO PESSOAL',
      'welcome_back': 'Bem-vindo novamente',
      'continue_finances': 'Continue organizando suas finanças.',
      'email': 'E-mail',
      'password': 'Senha',
      'remember_me': 'Lembrar de mim',
      'login': 'Entrar',
      'create_account': 'Criar conta',
      'forgot_password': 'Esqueceu sua senha?',
      'no_account': 'Ainda não tem uma conta? ',
      'incorrect_data': 'Dados incorretos',
      'missing_data': 'Dados faltando',
      'complete_fields': 'Preencha todos os campos.',
      'personal_budget': 'Orçamento',
      'notifications': 'Notificações',
      'security': 'Segurança',
      'language': 'Idioma',
      'categories': 'Categorias',
      'shopping_lists': 'Listas de compras',
      'terms': 'Termos e condições',
      'privacy': 'Aviso de privacidade',
      'settings': 'Configurações',
      'save': 'Salvar',
      'cancel': 'Cancelar',
      'done': 'Concluído',
      'select_language': 'Selecione um idioma',
      'spanish': 'Espanhol',
      'english': 'Inglês',
      'portuguese': 'Português',
      'english_native': 'English',
      'portuguese_native': 'Português',
      'spanish_native': 'Español',
      'unlock_mova': 'Desbloquear MOVA',
      'enter_pin': 'Digite seu PIN',
      'incorrect_pin': 'PIN incorreto',
      'incorrect_pin_message': 'O PIN informado está incorreto.',
      'loading_section': 'Carregando sua seção',
      'movements': 'Movimentações',
      'financial_activity': 'Sua atividade financeira em um só lugar.',
      'all': 'Todas',
      'savings': 'Poupança',
      'no_movements_filter': 'Não há movimentações neste filtro.',
      'add_income': 'Adicionar receita',
      'add_expense': 'Adicionar despesa',
      'income_help': 'Registre o dinheiro que recebeu',
      'expense_help': 'Registre como usou seu dinheiro',
      'expense': 'Despesa',
      'income_singular': 'Receita',
      'how_much_received': 'Quanto você recebeu?',
      'how_much': 'Quanto?',
      'what_spent': 'Com o que você gastou?',
      'income_source': 'Fonte da receita',
      'category': 'Categoria',
      'optional_note': 'Adicionar nota (opcional)',
      'save_income': 'Salvar receita',
      'save_movement': 'Salvar movimentação',
      'create_your_account': 'Crie sua conta',
      'take_control': 'Comece a assumir o controle das suas finanças.',
      'name': 'Nome',
      'enter_name': 'Digite seu nome',
      'enter_email': 'Digite seu e-mail',
      'create_password': 'Crie uma senha',
      'repeat_password': 'Repita sua senha',
      'my_goals': 'Minhas metas',
      'goals_subtitle': 'Transforme seus planos em objetivos',
      'new_goal': 'Nova meta',
      'free_savings': 'Poupança livre',
      'free_savings_help': 'Economize sem uma meta específica',
      'no_goals_yet': 'Você ainda não tem metas',
      'create_goal_savings':
          'Crie uma meta para dar um objetivo às suas economias.',
      'no_goals_home':
          'Você ainda não tem metas. Crie uma para começar a economizar.',
      'add': 'Adicionar',
      'withdraw': 'Retirar',
      'amount': 'Quantidade',
      'close': 'Fechar',
      'my_shopping': 'Minhas compras',
      'current': 'Atuais',
      'history': 'Histórico',
      'new_list': 'Nova lista',
      'no_completed_shopping': 'Ainda não há compras concluídas',
      'plan_first_shopping': 'Planeje sua primeira compra',
      'create_list': 'Criar lista',
      'understood': 'Entendido',
      'something_wrong': 'Algo deu errado',
      'ready': 'Concluído',
      'finance': 'FINANÇAS',
      'your_money': 'Seu dinheiro.\nSuas metas.\nSeu controle.',
      'welcome_subtitle': 'Organize, economize e avance com clareza.',
      'already_account': 'Já tenho uma conta',
      'protected_data': 'Seus dados estão protegidos',
      'logout': 'Sair',
      'close_session': 'Quer sair da sua conta?',
      'notifications_active': 'Notificações ativas',
      'savings_goals': 'Metas de poupança',
      'shopping': 'Compras',
      'view_all': 'Ver tudo',
      'no_summary': 'Não foi possível carregar o resumo',
      'recover_access': 'Recupere seu acesso',
      'new_password': 'Nova senha',
      'confirm_password': 'Confirmar senha',
      'update': 'Atualizar',
      'saving': 'Salvando...',
      'verify': 'Verificar',
      'cancelled': 'Cancelado',
      'account_options': 'Opções da conta',
      'preferences': 'Preferências e opções do MOVA',
      'exit_device': 'Sair da conta neste dispositivo',
      'choose_notifications': 'Escolha quais avisos deseja receber no MOVA.',
      'allow_notifications': 'Permitir notificações',
      'notifications_help': 'Ative ou pause todos os avisos do MOVA',
      'notification_types': 'TIPOS DE AVISO',
      'budget_help': 'Avisos relacionados ao seu orçamento',
      'goals_help': 'Lembretes para avançar em suas metas',
      'shopping_help': 'Lembretes de listas pendentes',
      'Sal de tu cuenta en este dispositivo':
          'Saia da sua conta neste dispositivo',
      'Aún no tienes metas. Crea una para empezar a ahorrar con un objetivo.':
          'Você ainda não tem metas. Crie uma para começar a economizar.',
      'Crea una meta para darle un objetivo a tus ahorros.':
          'Crie uma meta para dar um objetivo às suas economias.',
      'Gastos por categoría': 'Despesas por categoria',
      'Aún no hay gastos registrados en este periodo.':
          'Ainda não há despesas registradas neste período.',
      'Registra movimientos para obtener recomendaciones.':
          'Registre movimentações para obter recomendações.',
    },
  };

  String text(String key) =>
      _values[locale.languageCode]?[key] ?? _values['es']![key] ?? key;

  String _canonicalSpanish(String source) {
    for (final entry in _values['es']!.entries) {
      if (entry.key == source || entry.value == source) return entry.value;
    }
    for (final language in ['en', 'pt']) {
      for (final entry in _values[language]!.entries) {
        if (entry.value == source && _values['es']!.containsKey(entry.key)) {
          return _values['es']![entry.key]!;
        }
      }
      for (final entry in _phraseTranslations[language]!.entries) {
        if (entry.value == source) return entry.key;
      }
    }
    return source;
  }

  String translate(String source) {
    if (source.isEmpty) return source;
    source = _canonicalSpanish(source);
    if (locale.languageCode == 'es') return source;
    String? key;
    for (final entry in _values['es']!.entries) {
      if (entry.key == source || entry.value == source) {
        key = entry.key;
        break;
      }
    }
    if (key != null && _values[locale.languageCode]?.containsKey(key) == true) {
      return text(key);
    }
    final phrases = _phraseTranslations[locale.languageCode];
    if (phrases != null) {
      final exact = phrases[source];
      if (exact != null) return exact;
      var translated = source;
      final ordered = phrases.entries.toList()
        ..sort((a, b) => b.key.length.compareTo(a.key.length));
      for (final entry in ordered) {
        translated = translated.replaceAll(entry.key, entry.value);
      }
      if (translated != source) return translated;
    }
    return source;
  }

  static const _phraseTranslations = <String, Map<String, String>>{
    'en': {
      'No se pudo cargar': 'Could not load',
      'No se pudieron cargar': 'Could not load',
      'No hay movimientos': 'There are no movements',
      'Aún no tienes movimientos registrados':
          'You have no recorded movements yet',
      'Aún no tienes metas': 'You have no goals yet',
      'Crea una meta': 'Create a goal',
      'Meta actual': 'Current goal',
      'Dinero disponible': 'Available money',
      'Movimientos recientes': 'Recent movements',
      'Ver todos': 'View all',
      'Gastos por categoría': 'Expenses by category',
      'Aún no hay gastos registrados': 'No expenses recorded',
      'Registra movimientos': 'Record movements',
      'Ingresos registrados': 'Recorded income',
      'Tus gastos superan tus ingresos': 'Your expenses exceed your income',
      'Crear nueva meta': 'Create new goal',
      'Información de la meta': 'Goal information',
      'Elige un icono': 'Choose an icon',
      'Agregar imagen': 'Add image',
      'Modificar ahorro': 'Edit savings',
      'Retirar de la meta': 'Withdraw from goal',
      'Historial de la meta': 'Goal history',
      'No se puede deshacer': 'This cannot be undone',
      'Registrar gasto': 'Record expense',
      'Total estimado': 'Estimated total',
      'La lista está vacía': 'The list is empty',
      'Crea una contraseña': 'Create a password',
      'Mínimo 8 caracteres': 'At least 8 characters',
      'Verificando': 'Verifying',
      'Cerrar': 'Close',
      'Cancelar': 'Cancel',
      'Guardar': 'Save',
      'Eliminar': 'Delete',
      'Retirar': 'Withdraw',
      'Compartir': 'Share',
      'No se pudo actualizar el ahorro': 'Could not update savings',
      'Ahorro libre': 'Free savings',
      'Ahorra sin tener una meta específica': 'Save without a specific goal',
      'Ahorro retirado correctamente.': 'Savings withdrawn successfully.',
      'Ahorro agregado correctamente.': 'Savings added successfully.',
      'Retirar ahorro libre': 'Withdraw free savings',
      'Agregar ahorro libre': 'Add free savings',
      'Cantidad': 'Amount',
      'Cantidad ahorrada': 'Saved amount',
      'Disponible': 'Available',
      'Ahorrado': 'Saved',
      'Sin icono': 'No icon',
      'RESUMEN DE AHORRO': 'SAVINGS SUMMARY',
      'Disponible en la meta': 'Available in goal',
      'Todavía no hay movimientos en esta meta.':
          'There are no movements in this goal yet.',
      'Ahorro agregado': 'Savings added',
      'No se pudo crear la meta': 'Could not create the goal',
      'No se pudo retirar el dinero. Intenta nuevamente.':
          'Could not withdraw the money. Try again.',
      'Nombre de la meta': 'Goal name',
      'Ahorro inicial': 'Initial savings',
      'Se eliminarán también sus productos.':
          'Its products will also be deleted.',
      'Cuando finalices una lista aparecerá aquí.':
          'When you finish a list, it will appear here.',
      'Organiza tus productos y controla cuánto vas a gastar.':
          'Organize your products and track how much you will spend.',
      'Tu lista está vacía': 'Your list is empty',
      'Agrega productos para calcular tu compra.':
          'Add products to calculate your purchase.',
      'Crear lista': 'Create list',
      'Nueva lista': 'New list',
      'Renombrar lista': 'Rename list',
      'Nombre de la lista': 'List name',
      'Producto': 'Product',
      'Agregar producto': 'Add product',
      'Editar producto': 'Edit product',
      'Completa el producto con valores válidos.':
          'Complete the product with valid values.',
      'Monto inválido': 'Invalid amount',
      'Sin fecha': 'No date',
      'El precio se aplicará por:': 'The price will be applied per:',
      'Planifica tu próxima compra.': 'Plan your next purchase.',
      'Error de acceso': 'Access error',
      'Tus datos están protegidos': 'Your data is protected',
      'Contraseña actualizada. Ya puedes iniciar sesión.':
          'Password updated. You can now log in.',
      'No existe una cuenta con ese correo':
          'There is no account with that email',
      'No se pudo verificar tu identidad': 'Could not verify your identity',
      'Recupera tu acceso': 'Recover your access',
      'Identidad verificada': 'Identity verified',
      'Descripción': 'Description',
      'Fecha': 'Date',
      'El ingreso se agregará a tu saldo.':
          'The income will be added to your balance.',
      'Ingresa un monto válido mayor que cero':
          'Enter a valid amount greater than zero',
      'Escribe una descripción': 'Write a description',
      'Ingreso guardado correctamente': 'Income saved successfully',
      'Gasto guardado correctamente': 'Expense saved successfully',
      'Aún no tienes metas. Crea una para empezar a ahorrar con un objetivo.':
          'You have no goals yet. Create one to start saving toward a goal.',
      'Sal de tu cuenta en este dispositivo':
          'Sign out of your account on this device',
      'No se pudo cargar el historial': 'Could not load history',
      'Esta acción no se puede deshacer.': 'This action cannot be undone.',
      'El ahorro inicial no puede superar la meta':
          'Initial savings cannot exceed the goal',
      'Dale un propósito a tu ahorro': 'Give your savings a purpose',
      'Aún no hay gastos registrados en este periodo.':
          'There are no expenses recorded in this period.',
      'Aún no hay ingresos registrados en este periodo.':
          'There is no income recorded in this period.',
      'No se pudo cargar el análisis': 'Could not load the analysis',
      'No se pudo cargar el resumen': 'Could not load the summary',
      'Actualizado el 23 de septiembre de 2026': 'Updated September 23, 2026',
      'Acepto los ': 'I accept the ',
      'aviso de privacidad': 'privacy notice',
      'Contraseña débil': 'Weak password',
      'Aceptación requerida': 'Acceptance required',
      'Revisa tu nombre, correo y contraseña.':
          'Check your name, email, and password.',
      'Revisa tu correo y contraseña e inténtalo nuevamente.':
          'Check your email and password and try again.',
      'No fue posible iniciar sesión.': 'Could not log in.',
      'Escribe tu correo electrónico': 'Enter your email',
      'Usa mínimo 8 caracteres': 'Use at least 8 characters',
      'Administra tu información personal': 'Manage your personal information',
      'Nombre': 'Name',
      'Define cuánto quieres gastar': 'Set how much you want to spend',
      'Protege tu información': 'Protect your information',
      'Importar datos': 'Import data',
      'Importa información existente': 'Import existing information',
      'Consulta cómo se tratan tus datos': 'Learn how your data is handled',
      'Cerrar sesión': 'Log out',
      'Eliminar cuenta': 'Delete account',
      'Esta acción es permanente.': 'This action is permanent.',
      'Se eliminarán tu cuenta, movimientos, metas, listas y configuraciones. No podrás recuperar estos datos.': 'Your account, movements, goals, lists, and settings will be deleted. You will not be able to recover this data.',
      'No se pudo eliminar la cuenta. Intenta nuevamente.':
          'Could not delete the account. Please try again.',
      'Más': 'More',
      'Importar respaldo': 'Import backup',
      'El archivo no tiene un formato válido': 'The file format is invalid',
      'Elige qué recordatorios quieres recibir':
          'Choose which reminders you want to receive',
      'Avisos relacionados con tu límite mensual':
          'Alerts related to your monthly limit',
      'Lista de compras': 'Shopping list',
      'Versión 1.0.0  ·  Finanzas personales':
          'Version 1.0.0  ·  Personal finance',
      'Biometría no disponible': 'Biometrics unavailable',
      'Verificación no completada': 'Verification not completed',
      'Elige una sola forma de proteger tu sesión':
          'Choose one way to protect your session',
      'Huella o biometría': 'Fingerprint or biometrics',
      'Usa el sensor del dispositivo': 'Use the device sensor',
      'Números (PIN)': 'Numbers (PIN)',
      'Crea un código de 4 a 8 dígitos': 'Create a 4 to 8 digit code',
      'Desactivar protección': 'Disable protection',
      'Crear PIN': 'Create PIN',
      'PIN de 4 a 8 dígitos': '4 to 8 digit PIN',
      'Ingresa un presupuesto válido': 'Enter a valid budget',
      'Presupuesto actualizado': 'Budget updated',
      'Controla tus gastos sin perder de vista tu límite':
          'Track your spending without losing sight of your limit',
      'Se reinicia cada lunes y considera tus gastos de esta semana.':
          'It resets every Monday and considers your spending for this week.',
      'Se reinicia el primer día de cada mes.':
          'It resets on the first day of each month.',
      'Nombre de la categoría': 'Category name',
      'Icono o emoji': 'Icon or emoji',
      'Puedes usar un emoji para identificarla más rápido.':
          'You can use an emoji to identify it faster.',
      'Pega aquí el JSON exportado desde MOVA. Tus datos actuales no se eliminarán.': 'Paste the JSON exported from MOVA here. Your current data will not be deleted.',
      'MOVA está diseñada con un enfoque offline-first. Tus datos principales se mantienen en tu dispositivo.': 'MOVA is designed with an offline-first approach. Your main data stays on your device.',
      'Organiza ingresos, gastos, metas y compras en un solo espacio, de forma clara y sencilla.': 'Organize income, expenses, goals, and purchases in one clear, simple space.',
      'Lee estas condiciones para conocer el uso responsable de MOVA.':
          'Read these terms to learn about responsible use of MOVA.',
      'Consulta qué información se guarda y cómo puedes administrar tus datos.':
          'Learn what information is stored and how you can manage your data.',
      'Límite mensual': 'Monthly limit',
      'Quitar límite': 'Remove limit',
      'Moneda de la aplicación': 'App currency',
      'Esa categoría ya existe para ese tipo':
          'That category already exists for this type',
      'Aún no tienes categorías personalizadas':
          'You have no custom categories yet',
      '¿Qué tipo de movimiento será?': 'What type of movement will it be?',
      'Crear categoría': 'Create category',
      'Nueva categoría': 'New category',
      'Personaliza tus movimientos para encontrarlos fácilmente':
          'Customize your movements to find them easily',
      'FINANZAS': 'FINANCES',
      'APLICACIÓN': 'APPLICATION',
      'DATOS': 'DATA',
      'INFORMACIÓN': 'INFORMATION',
      'CUENTA': 'ACCOUNT',
      'Administra tus categorías de ingresos y gastos':
          'Manage your income and expense categories',
      'Organiza productos, calcula y registra tus compras':
          'Organize products, calculate, and record your purchases',
      'Gestiona tus recordatorios': 'Manage your reminders',
      'Consulta las condiciones de uso': 'View the terms of use',
      'Acerca de MOVA': 'About MOVA',
      'Exportar datos': 'Export data',
      'Descarga tus movimientos': 'Download your movements',
      'Todo lo que necesitas para controlar MOVA':
          'Everything you need to manage MOVA',
      'Crea una meta para darle un objetivo a tus ahorros.':
          'Create a goal to give your savings a purpose.',
      'Al crear una cuenta y utilizar MOVA confirmas que leíste, comprendiste y aceptas estos términos.': 'By creating an account and using MOVA, you confirm that you have read, understood, and accept these terms.',
      'MOVA es una herramienta de organización financiera personal para registrar ingresos, gastos, metas, presupuestos y listas.': 'MOVA is a personal finance organization tool for recording income, expenses, goals, budgets, and lists.',
      'Eres responsable de mantener la confidencialidad de tu correo y contraseña, así como de la actividad realizada desde tu dispositivo.': 'You are responsible for keeping your email and password confidential, as well as for activity performed from your device.',
      'Los cálculos y análisis son orientativos y dependen de los datos que registres. MOVA no sustituye asesoría financiera profesional.': 'Calculations and analyses are for guidance and depend on the data you enter. MOVA does not replace professional financial advice.',
      'No debes acceder a cuentas ajenas, alterar la aplicación ni utilizar MOVA para actividades ilegales.': 'You must not access other accounts, alter the app, or use MOVA for illegal activities.',
      'MOVA puede guardar tu nombre, correo, contraseña, foto de perfil, movimientos, metas, presupuestos, categorías y listas.': 'MOVA may store your name, email, password, profile photo, movements, goals, budgets, categories, and lists.',
      'Utilizamos esta información para proteger tu cuenta, mostrar tus finanzas, generar resúmenes y conservar tus preferencias.': 'We use this information to protect your account, show your finances, generate summaries, and keep your preferences.',
      'La información financiera de MOVA se almacena localmente en el dispositivo para que puedas utilizar la aplicación.': 'MOVA financial information is stored locally on the device so you can use the app.',
      'Puedes editar o eliminar la información desde las funciones disponibles de MOVA, incluida la eliminación de tu cuenta.': 'You can edit or delete information using MOVA features, including deleting your account.',
      'Tu avance acumulado': 'Your accumulated progress',
      'Registra movimientos para obtener recomendaciones.':
          'Record movements to get recommendations.',
      'Tus gastos superan tus ingresos en':
          'Your expenses exceed your income by',
      'Tu balance positivo es de': 'Your positive balance is',
      'de': 'of',
      'establecidos': 'set',
      'completado': 'completed',
      'Guardando...': 'Saving...',
      'Actualizar': 'Update',
      'Quitar foto': 'Remove photo',
      'Agregar': 'Add',
      'Antes de continuar': 'Before continuing',
      'Aporte': 'Contribution',
      'Borra tu cuenta y todos sus datos':
          'Delete your account and all its data',
      'Compartir meta': 'Share goal',
      'Compra incompleta': 'Incomplete purchase',
      'Contenido de la copia': 'Backup contents',
      'Copia lista': 'Copy ready',
      'Copiar de nuevo': 'Copy again',
      'Crear QR': 'Create QR',
      'Crear meta': 'Create goal',
      'Cuenta existente': 'Existing account',
      'Define qué necesitas y calcula el costo al instante.':
          'Define what you need and calculate the cost instantly.',
      'Desbloquear': 'Unlock',
      'Editar': 'Edit',
      'Editar información de tu cuenta': 'Edit your account information',
      'Editar nombre': 'Edit name',
      'Ej. 8,000.00': 'E.g. 8,000.00',
      'Ej. Comida, transporte o freelance':
          'E.g. Food, transport, or freelance',
      'Elige un emoji': 'Choose an emoji',
      'Eliminar lista': 'Delete list',
      'Eliminar meta': 'Delete goal',
      'Eliminar producto': 'Delete product',
      'Escribe tu nombre': 'Enter your name',
      'Escribe una cantidad mayor a cero.':
          'Enter an amount greater than zero.',
      'Finalizar': 'Finish',
      'Importar': 'Import',
      'Licencias': 'Licenses',
      'Límite mensual (': 'Monthly limit (',
      'Mensual': 'Monthly',
      'Moneda general de MOVA': 'MOVA default currency',
      'Monto a retirar': 'Amount to withdraw',
      'Monto del aporte': 'Contribution amount',
      'No se pudo abrir el selector de imágenes:':
          'Could not open the image picker:',
      'No se pudo actualizar el ahorro:': 'Could not update savings:',
      'No se pudo cargar el análisis:': 'Could not load the analysis:',
      'No se pudo cargar el historial:': 'Could not load the history:',
      'No se pudo cargar el resumen:': 'Could not load the summary:',
      'No se pudo completar': 'Could not complete',
      'No se pudo guardar la preferencia.': 'Could not save the preference.',
      'El correo electrónico ya está registrado.':
          'This email is already registered.',
      'No se pudo guardar el movimiento:': 'Could not save the movement:',
      'La biometría no está disponible o no está configurada en este dispositivo.':
          'Biometrics are unavailable or not configured on this device.',
      'La verificación fue cancelada.': 'Verification was canceled.',
      'No se pudo verificar tu identidad. Confirma que tienes una huella o rostro registrado en los ajustes del teléfono.': 'Identity verification failed. Confirm that a fingerprint or face is registered in your phone settings.',
      'El sistema biométrico devolvió un error. Verifica la biometría configurada en tu teléfono e inténtalo nuevamente.': 'The biometric system returned an error. Check the biometrics configured on your phone and try again.',
      'Presupuesto excedido': 'Budget exceeded',
      'Precio pendiente': 'Price pending',
      'Precio opcional': 'Optional price',
      'Opcional · JPG, PNG o WebP': 'Optional · JPG, PNG, or WebP',
      'PROGRESO DE LA META': 'GOAL PROGRESS',
      'Permite recibir recordatorios de Mova':
          'Allow receiving reminders from Mova',
      'Por ': 'Per ',
      'Presupuesto ': 'Budget ',
      'QR de aporte': 'Contribution QR',
      'Recordatorios para avanzar en tus metas':
          'Reminders to progress toward your goals',
      'Registrar compra': 'Record purchase',
      'Respaldo local': 'Local backup',
      'Tu información está preparada para guardarse':
          'Your information is ready to be saved',
      'Agrega información de otra copia de MOVA':
          'Add information from another MOVA backup',
      'Solo se importan movimientos válidos. La información existente se conserva.': 'Only valid movements are imported. Existing information is preserved.',
      'Cambiar la moneda no modifica el límite configurado.':
          'Changing the currency does not modify the configured limit.',
      'El archivo se copió al portapapeles. Pégalo en un lugar seguro para conservarlo.': 'The file was copied to the clipboard. Paste it somewhere safe to keep it.',
      'movimientos': 'movements',
      'metas': 'goals',
      'listas': 'lists',
      'Se aplicará a ingresos, gastos, metas, compras y presupuesto. No convierte cantidades existentes.': 'It applies to income, expenses, goals, purchases, and budgets. It does not convert existing amounts.',
      'Tu límite semanal quedó en': 'Your weekly limit is set to',
      'Tu límite mensual quedó en': 'Your monthly limit is set to',
      'Revisa el producto': 'Review the product',
      'Semanal': 'Weekly',
      'Total': 'Total',
      'Tu balance positivo es de ': 'Your positive balance is ',
      'Tu dinero, en movimiento.': 'Your money, in motion.',
      'Usa un nombre fácil de reconocer.': 'Use an easy-to-recognize name.',
      'Versión 1.0.0': 'Version 1.0.0',
      '¿De dónde provino este ingreso?': 'Where did this income come from?',
      '¿Ya tienes una cuenta?': 'Already have an account?',
      'Activar notificaciones': 'Enable notifications',
      'Agrega al menos un producto antes de finalizar.':
          'Add at least one product before finishing.',
      'movimientos importados': 'movements imported',
      'y el ': 'and the ',
      'Verificando...': 'Verifying...',
      'Verificar con huella': 'Verify with fingerprint',
      'Escribe una cantidad mayor a cero': 'Enter an amount greater than zero.',
      'Ingresa un monto mayor que cero': 'Enter an amount greater than zero',
      'Ingresa un correo electrónico válido.': 'Enter a valid email address.',
      'Usa al menos 8 caracteres, una mayúscula, un número o un símbolo.':
          'Use at least 8 characters, one uppercase letter, number, or symbol.',
      'Las contraseñas no coinciden.': 'Passwords do not match.',
      'Debes aceptar los términos y condiciones.':
          'You must accept the terms and conditions.',
      'Términos y condiciones': 'Terms and conditions',
      'Aviso de privacidad': 'Privacy notice',
      'meta activa': 'active goal',
      'metas activas': 'active goals',
      'Retiro': 'Withdrawal',
      'Compra finalizada': 'Purchase completed',
      'Control de compra': 'Purchase tracking',
      'Agregado al carrito': 'Added to cart',
      'Pendiente por comprar': 'Pending purchase',
      'gastado hasta hoy': 'spent today',
      'Sueldo': 'Salary',
      'Freelance': 'Freelance',
      'Inversión': 'Investment',
      'Regalo': 'Gift',
      'Venta': 'Sale',
      'Otro': 'Other',
      'Comida': 'Food',
      'Transporte': 'Transport',
      'Compras': 'Shopping',
      'Hogar': 'Home',
      'Entretenimiento': 'Entertainment',
      'Ahorro': 'Savings',
      'Ahorro sin meta': 'Savings without goal',
      'Otros': 'Others',
      'Aparta una cantidad sin asociarla a una meta.':
          'Set aside an amount without linking it to a goal.',
      'Lista en curso': 'List in progress',
      'No se pudieron cargar los movimientos:': 'Could not load movements:',
      'Las contraseñas no coinciden': 'Passwords do not match',
    },
    'pt': {
      'No se pudo cargar': 'Não foi possível carregar',
      'No se pudieron cargar': 'Não foi possível carregar',
      'No hay movimientos': 'Não há movimentações',
      'Aún no tienes movimientos registrados':
          'Você ainda não tem movimentações registradas',
      'Aún no tienes metas': 'Você ainda não tem metas',
      'Crea una meta': 'Crie uma meta',
      'Meta actual': 'Meta atual',
      'Dinero disponible': 'Dinheiro disponível',
      'Movimientos recientes': 'Movimentações recentes',
      'Ver todos': 'Ver tudo',
      'Gastos por categoría': 'Despesas por categoria',
      'Aún no hay gastos registrados': 'Ainda não há despesas registradas',
      'Registra movimientos': 'Registre movimentações',
      'Crear nueva meta': 'Criar nova meta',
      'Información de la meta': 'Informações da meta',
      'Elige un icono': 'Escolha um ícone',
      'Agregar imagen': 'Adicionar imagem',
      'Modificar ahorro': 'Editar poupança',
      'Retirar de la meta': 'Retirar da meta',
      'Historial de la meta': 'Histórico da meta',
      'No se puede deshacer': 'Esta ação não pode ser desfeita',
      'Registrar gasto': 'Registrar despesa',
      'Agregar producto': 'Adicionar produto',
      'Total estimado': 'Total estimado',
      'La lista está vacía': 'A lista está vazia',
      'Las contraseñas no coinciden': 'As senhas não coincidem',
      'Mínimo 8 caracteres': 'Mínimo de 8 caracteres',
      'Verificando': 'Verificando',
      'Identidad verificada': 'Identidade verificada',
      'Cerrar': 'Fechar',
      'Cancelar': 'Cancelar',
      'Guardar': 'Salvar',
      'Eliminar': 'Excluir',
      'Retirar': 'Retirar',
      'Compartir': 'Compartilhar',
      'No se pudo actualizar el ahorro':
          'Não foi possível atualizar a poupança',
      'Ahorro libre': 'Poupança livre',
      'Ahorra sin tener una meta específica':
          'Economize sem uma meta específica',
      'Ahorro retirado correctamente.': 'Poupança retirada com sucesso.',
      'Ahorro agregado correctamente.': 'Poupança adicionada com sucesso.',
      'Retirar ahorro libre': 'Retirar poupança livre',
      'Agregar ahorro libre': 'Adicionar poupança livre',
      'Cantidad': 'Valor',
      'Cantidad ahorrada': 'Valor economizado',
      'Disponible': 'Disponível',
      'Ahorrado': 'Economizado',
      'Sin icono': 'Sem ícone',
      'RESUMEN DE AHORRO': 'RESUMO DA POUPANÇA',
      'Disponible en la meta': 'Disponível na meta',
      'Todavía no hay movimientos en esta meta.':
          'Ainda não há movimentações nesta meta.',
      'Ahorro agregado': 'Poupança adicionada',
      'No se pudo crear la meta': 'Não foi possível criar a meta',
      'No se pudo retirar el dinero. Intenta nuevamente.':
          'Não foi possível retirar o dinheiro. Tente novamente.',
      'Nombre de la meta': 'Nome da meta',
      'Ahorro inicial': 'Poupança inicial',
      'Se eliminarán también sus productos.':
          'Os produtos também serão excluídos.',
      'Cuando finalices una lista aparecerá aquí.':
          'Quando você concluir uma lista, ela aparecerá aqui.',
      'Organiza tus productos y controla cuánto vas a gastar.':
          'Organize seus produtos e controle quanto vai gastar.',
      'Tu lista está vacía': 'Sua lista está vazia',
      'Agrega productos para calcular tu compra.':
          'Adicione produtos para calcular sua compra.',
      'Crear lista': 'Criar lista',
      'Nueva lista': 'Nova lista',
      'Renombrar lista': 'Renomear lista',
      'Nombre de la lista': 'Nome da lista',
      'Producto': 'Produto',
      'Editar producto': 'Editar produto',
      'Completa el producto con valores válidos.':
          'Preencha o produto com valores válidos.',
      'Monto inválido': 'Valor inválido',
      'Sin fecha': 'Sem data',
      'El precio se aplicará por:': 'O preço será aplicado por:',
      'Planifica tu próxima compra.': 'Planeje sua próxima compra.',
      'Error de acceso': 'Erro de acesso',
      'Tus datos están protegidos': 'Seus dados estão protegidos',
      'Contraseña actualizada. Ya puedes iniciar sesión.':
          'Senha atualizada. Você já pode entrar.',
      'No existe una cuenta con ese correo':
          'Não existe uma conta com esse e-mail',
      'No se pudo verificar tu identidad':
          'Não foi possível verificar sua identidade',
      'Recupera tu acceso': 'Recupere seu acesso',
      'Descripción': 'Descrição',
      'Fecha': 'Data',
      'El ingreso se agregará a tu saldo.':
          'A receita será adicionada ao seu saldo.',
      'Ingresa un monto válido mayor que cero':
          'Insira um valor válido maior que zero',
      'Escribe una descripción': 'Escreva uma descrição',
      'Ingreso guardado correctamente': 'Receita salva com sucesso',
      'Gasto guardado correctamente': 'Despesa salva com sucesso',
      'Aún no tienes metas. Crea una para empezar a ahorrar con un objetivo.':
          'Você ainda não tem metas. Crie uma para começar a economizar.',
      'Sal de tu cuenta en este dispositivo':
          'Saia da sua conta neste dispositivo',
      'No se pudo cargar el historial': 'Não foi possível carregar o histórico',
      'Esta acción no se puede deshacer.': 'Esta ação não pode ser desfeita.',
      'El ahorro inicial no puede superar la meta':
          'A poupança inicial não pode superar a meta',
      'Dale un propósito a tu ahorro': 'Dê um propósito à sua poupança',
      'Aún no hay gastos registrados en este periodo.':
          'Ainda não há despesas registradas neste período.',
      'Aún no hay ingresos registrados en este periodo.':
          'Ainda não há receitas registradas neste período.',
      'No se pudo cargar el análisis': 'Não foi possível carregar a análise',
      'No se pudo cargar el resumen': 'Não foi possível carregar o resumo',
      'Actualizado el 23 de septiembre de 2026':
          'Atualizado em 23 de setembro de 2026',
      'Acepto los ': 'Aceito o ',
      'aviso de privacidad': 'aviso de privacidade',
      'Contraseña débil': 'Senha fraca',
      'Aceptación requerida': 'Aceitação necessária',
      'Revisa tu nombre, correo y contraseña.':
          'Verifique seu nome, e-mail e senha.',
      'Revisa tu correo y contraseña e inténtalo nuevamente.':
          'Verifique seu e-mail e senha e tente novamente.',
      'No fue posible iniciar sesión.': 'Não foi possível entrar.',
      'Escribe tu correo electrónico': 'Digite seu e-mail',
      'Usa mínimo 8 caracteres': 'Use pelo menos 8 caracteres',
      'Administra tu información personal':
          'Gerencie suas informações pessoais',
      'Nombre': 'Nome',
      'Define cuánto quieres gastar': 'Defina quanto quer gastar',
      'Protege tu información': 'Proteja suas informações',
      'Importar datos': 'Importar dados',
      'Importa información existente': 'Importe informações existentes',
      'Consulta cómo se tratan tus datos': 'Veja como seus dados são tratados',
      'Cerrar sesión': 'Sair',
      'Eliminar cuenta': 'Excluir conta',
      'Esta acción es permanente.': 'Esta ação é permanente.',
      'Se eliminarán tu cuenta, movimientos, metas, listas y configuraciones. No podrás recuperar estos datos.': 'Sua conta, movimentações, metas, listas e configurações serão excluídas. Não será possível recuperar esses dados.',
      'No se pudo eliminar la cuenta. Intenta nuevamente.':
          'Não foi possível excluir a conta. Tente novamente.',
      'Más': 'Mais',
      'Importar respaldo': 'Importar backup',
      'El archivo no tiene un formato válido':
          'O formato do arquivo é inválido',
      'Elige qué recordatorios quieres recibir':
          'Escolha quais lembretes deseja receber',
      'Avisos relacionados con tu límite mensual':
          'Avisos relacionados ao seu limite mensal',
      'Versión 1.0.0  ·  Finanzas personales':
          'Versão 1.0.0  ·  Finanças pessoais',
      'Biometría no disponible': 'Biometria indisponível',
      'Verificación no completada': 'Verificação não concluída',
      'Elige una sola forma de proteger tu sesión':
          'Escolha uma forma de proteger sua sessão',
      'Huella o biometría': 'Impressão digital ou biometria',
      'Usa el sensor del dispositivo': 'Use o sensor do dispositivo',
      'Números (PIN)': 'Números (PIN)',
      'Crea un código de 4 a 8 dígitos': 'Crie um código de 4 a 8 dígitos',
      'Desactivar protección': 'Desativar proteção',
      'Crear PIN': 'Criar PIN',
      'PIN de 4 a 8 dígitos': 'PIN de 4 a 8 dígitos',
      'Ingresa un presupuesto válido': 'Insira um orçamento válido',
      'Presupuesto actualizado': 'Orçamento atualizado',
      'Controla tus gastos sin perder de vista tu límite':
          'Controle seus gastos sem perder de vista seu limite',
      'Se reinicia cada lunes y considera tus gastos de esta semana.':
          'Reinicia toda segunda-feira e considera seus gastos desta semana.',
      'Se reinicia el primer día de cada mes.':
          'Reinicia no primeiro dia de cada mês.',
      'Nombre de la categoría': 'Nome da categoria',
      'Icono o emoji': 'Ícone ou emoji',
      'Puedes usar un emoji para identificarla más rápido.':
          'Você pode usar um emoji para identificá-la mais rapidamente.',
      'Pega aquí el JSON exportado desde MOVA. Tus datos actuales no se eliminarán.': 'Cole aqui o JSON exportado do MOVA. Seus dados atuais não serão excluídos.',
      'MOVA está diseñada con un enfoque offline-first. Tus datos principales se mantienen en tu dispositivo.': 'O MOVA foi projetado com uma abordagem offline-first. Seus dados principais ficam no dispositivo.',
      'Organiza ingresos, gastos, metas y compras en un solo espacio, de forma clara y sencilla.': 'Organize receitas, despesas, metas e compras em um só lugar, de forma clara e simples.',
      'Lee estas condiciones para conocer el uso responsable de MOVA.':
          'Leia estas condições para conhecer o uso responsável do MOVA.',
      'Consulta qué información se guarda y cómo puedes administrar tus datos.': 'Veja quais informações são armazenadas e como você pode gerenciar seus dados.',
      'Límite mensual': 'Limite mensal',
      'Quitar límite': 'Remover limite',
      'Moneda de la aplicación': 'Moeda do aplicativo',
      'Esa categoría ya existe para ese tipo':
          'Essa categoria já existe para esse tipo',
      'Aún no tienes categorías personalizadas':
          'Você ainda não tem categorias personalizadas',
      '¿Qué tipo de movimiento será?': 'Que tipo de movimentação será?',
      'Crear categoría': 'Criar categoria',
      'Nueva categoría': 'Nova categoria',
      'Personaliza tus movimientos para encontrarlos fácilmente':
          'Personalize suas movimentações para encontrá-las facilmente',
      'FINANZAS': 'FINANÇAS',
      'APLICACIÓN': 'APLICATIVO',
      'DATOS': 'DADOS',
      'INFORMACIÓN': 'INFORMAÇÕES',
      'CUENTA': 'CONTA',
      'Administra tus categorías de ingresos y gastos':
          'Gerencie suas categorias de receitas e despesas',
      'Organiza productos, calcula y registra tus compras':
          'Organize produtos, calcule e registre suas compras',
      'Gestiona tus recordatorios': 'Gerencie seus lembretes',
      'Consulta las condiciones de uso': 'Veja as condições de uso',
      'Acerca de MOVA': 'Sobre o MOVA',
      'Exportar datos': 'Exportar dados',
      'Descarga tus movimientos': 'Baixe suas movimentações',
      'Todo lo que necesitas para controlar MOVA':
          'Tudo o que você precisa para controlar o MOVA',
      'Crea una meta para darle un objetivo a tus ahorros.':
          'Crie uma meta para dar um objetivo às suas economias.',
      'Al crear una cuenta y utilizar MOVA confirmas que leíste, comprendiste y aceptas estos términos.': 'Ao criar uma conta e usar o MOVA, você confirma que leu, entendeu e aceita estes termos.',
      'MOVA es una herramienta de organización financiera personal para registrar ingresos, gastos, metas, presupuestos y listas.': 'O MOVA é uma ferramenta de organização financeira pessoal para registrar receitas, despesas, metas, orçamentos e listas.',
      'Eres responsable de mantener la confidencialidad de tu correo y contraseña, así como de la actividad realizada desde tu dispositivo.': 'Você é responsável por manter seu e-mail e senha em sigilo, assim como pela atividade realizada no seu dispositivo.',
      'Los cálculos y análisis son orientativos y dependen de los datos que registres. MOVA no sustituye asesoría financiera profesional.': 'Os cálculos e análises são orientativos e dependem dos dados registrados. O MOVA não substitui aconselhamento financeiro profissional.',
      'No debes acceder a cuentas ajenas, alterar la aplicación ni utilizar MOVA para actividades ilegales.': 'Você não deve acessar contas de terceiros, alterar o aplicativo ou usar o MOVA para atividades ilegais.',
      'MOVA puede guardar tu nombre, correo, contraseña, foto de perfil, movimientos, metas, presupuestos, categorías y listas.': 'O MOVA pode armazenar seu nome, e-mail, senha, foto de perfil, movimentações, metas, orçamentos, categorias e listas.',
      'Utilizamos esta información para proteger tu cuenta, mostrar tus finanzas, generar resúmenes y conservar tus preferencias.': 'Usamos essas informações para proteger sua conta, mostrar suas finanças, gerar resumos e manter suas preferências.',
      'La información financiera de MOVA se almacena localmente en el dispositivo para que puedas utilizar la aplicación.': 'As informações financeiras do MOVA são armazenadas localmente no dispositivo para que você possa usar o aplicativo.',
      'Puedes editar o eliminar la información desde las funciones disponibles de MOVA, incluida la eliminación de tu cuenta.': 'Você pode editar ou excluir informações usando os recursos do MOVA, incluindo a exclusão da sua conta.',
      'Tu avance acumulado': 'Seu progresso acumulado',
      'Registra movimientos para obtener recomendaciones.':
          'Registre movimentações para obter recomendações.',
      'Tus gastos superan tus ingresos en':
          'Suas despesas superam suas receitas em',
      'Tu balance positivo es de': 'Seu saldo positivo é de',
      'de': 'de',
      'establecidos': 'definidos',
      'completado': 'concluído',
      'Guardando...': 'Salvando...',
      'Actualizar': 'Atualizar',
      'Quitar foto': 'Remover foto',
      'Agregar': 'Adicionar',
      'Antes de continuar': 'Antes de continuar',
      'Aporte': 'Contribuição',
      'Borra tu cuenta y todos sus datos':
          'Exclua sua conta e todos os seus dados',
      'Compartir meta': 'Compartilhar meta',
      'Compra incompleta': 'Compra incompleta',
      'Contenido de la copia': 'Conteúdo do backup',
      'Copia lista': 'Cópia pronta',
      'Copiar de nuevo': 'Copiar novamente',
      'Crear QR': 'Criar QR',
      'Crear meta': 'Criar meta',
      'Cuenta existente': 'Conta existente',
      'Define qué necesitas y calcula el costo al instante.':
          'Defina o que precisa e calcule o custo instantaneamente.',
      'Desbloquear': 'Desbloquear',
      'Editar': 'Editar',
      'Editar información de tu cuenta': 'Editar as informações da sua conta',
      'Editar nombre': 'Editar nome',
      'Ej. 8,000.00': 'Ex. 8.000,00',
      'Ej. Comida, transporte o freelance':
          'Ex. Comida, transporte ou freelance',
      'Elige un emoji': 'Escolha um emoji',
      'Eliminar lista': 'Excluir lista',
      'Eliminar meta': 'Excluir meta',
      'Eliminar producto': 'Excluir produto',
      'Escribe tu nombre': 'Digite seu nome',
      'Escribe una cantidad mayor a cero.': 'Digite um valor maior que zero.',
      'Finalizar': 'Concluir',
      'Importar': 'Importar',
      'Licencias': 'Licenças',
      'Límite mensual (': 'Limite mensal (',
      'Mensual': 'Mensal',
      'Moneda general de MOVA': 'Moeda padrão do MOVA',
      'Monto a retirar': 'Valor a retirar',
      'Monto del aporte': 'Valor da contribuição',
      'No se pudo abrir el selector de imágenes:':
          'Não foi possível abrir o seletor de imagens:',
      'No se pudo actualizar el ahorro:':
          'Não foi possível atualizar a poupança:',
      'No se pudo cargar el análisis:': 'Não foi possível carregar a análise:',
      'No se pudo cargar el historial:':
          'Não foi possível carregar o histórico:',
      'No se pudo cargar el resumen:': 'Não foi possível carregar o resumo:',
      'No se pudo completar': 'Não foi possível concluir',
      'No se pudo guardar la preferencia.':
          'Não foi possível salvar a preferência.',
      'El correo electrónico ya está registrado.':
          'Este e-mail já está registrado.',
      'No se pudo guardar el movimiento:':
          'Não foi possível salvar a movimentação:',
      'La biometría no está disponible o no está configurada en este dispositivo.': 'A biometria não está disponível ou não está configurada neste dispositivo.',
      'La verificación fue cancelada.': 'A verificação foi cancelada.',
      'No se pudo verificar tu identidad. Confirma que tienes una huella o rostro registrado en los ajustes del teléfono.': 'Não foi possível verificar sua identidade. Confirme se há uma impressão digital ou rosto cadastrado nas configurações do telefone.',
      'El sistema biométrico devolvió un error. Verifica la biometría configurada en tu teléfono e inténtalo nuevamente.': 'O sistema biométrico retornou um erro. Verifique a biometria configurada no telefone e tente novamente.',
      'Presupuesto excedido': 'Orçamento excedido',
      'Precio pendiente': 'Preço pendente',
      'Precio opcional': 'Preço opcional',
      'Opcional · JPG, PNG o WebP': 'Opcional · JPG, PNG ou WebP',
      'PROGRESO DE LA META': 'PROGRESSO DA META',
      'Permite recibir recordatorios de Mova':
          'Permitir receber lembretes do Mova',
      'Por ': 'Por ',
      'Presupuesto ': 'Orçamento ',
      'QR de aporte': 'QR de contribuição',
      'Recordatorios para avanzar en tus metas':
          'Lembretes para avançar nas suas metas',
      'Registrar compra': 'Registrar compra',
      'Respaldo local': 'Backup local',
      'Tu información está preparada para guardarse':
          'Suas informações estão prontas para serem salvas',
      'Agrega información de otra copia de MOVA':
          'Adicione informações de outro backup do MOVA',
      'Solo se importan movimientos válidos. La información existente se conserva.': 'Somente movimentações válidas são importadas. As informações existentes são preservadas.',
      'Cambiar la moneda no modifica el límite configurado.':
          'Alterar a moeda não modifica o limite configurado.',
      'El archivo se copió al portapapeles. Pégalo en un lugar seguro para conservarlo.': 'O arquivo foi copiado para a área de transferência. Cole-o em um local seguro para guardá-lo.',
      'movimientos': 'movimentações',
      'metas': 'metas',
      'listas': 'listas',
      'Se aplicará a ingresos, gastos, metas, compras y presupuesto. No convierte cantidades existentes.': 'Aplica-se a receitas, despesas, metas, compras e orçamentos. Não converte valores existentes.',
      'Tu límite semanal quedó en': 'Seu limite semanal ficou em',
      'Tu límite mensual quedó en': 'Seu limite mensal ficou em',
      'Revisa el producto': 'Revise o produto',
      'Semanal': 'Semanal',
      'Total': 'Total',
      'Tu balance positivo es de ': 'Seu saldo positivo é de ',
      'Tu dinero, en movimiento.': 'Seu dinheiro em movimento.',
      'Usa un nombre fácil de reconocer.': 'Use um nome fácil de reconhecer.',
      'Versión 1.0.0': 'Versão 1.0.0',
      '¿De dónde provino este ingreso?': 'De onde veio esta receita?',
      '¿Ya tienes una cuenta?': 'Já tem uma conta?',
      'Activar notificaciones': 'Ativar notificações',
      'Agrega al menos un producto antes de finalizar.':
          'Adicione pelo menos um produto antes de concluir.',
      'movimientos importados': 'movimentações importadas',
      'y el ': 'e o ',
      'Verificando...': 'Verificando...',
      'Verificar con huella': 'Verificar com impressão digital',
      'Escribe una cantidad mayor a cero': 'Digite um valor maior que zero.',
      'Ingresa un monto mayor que cero': 'Digite um valor maior que zero',
      'Ingresa un correo electrónico válido.': 'Digite um e-mail válido.',
      'Usa al menos 8 caracteres, una mayúscula, un número o un símbolo.': 'Use pelo menos 8 caracteres, uma letra maiúscula, número ou símbolo.',
      'Las contraseñas no coinciden.': 'As senhas não coincidem.',
      'Debes aceptar los términos y condiciones.':
          'Você deve aceitar os termos e condições.',
      'Términos y condiciones': 'Termos e condições',
      'Aviso de privacidad': 'Aviso de privacidade',
      'meta activa': 'meta ativa',
      'metas activas': 'metas ativas',
      'Retiro': 'Retirada',
      'Compra finalizada': 'Compra concluída',
      'Control de compra': 'Controle da compra',
      'Agregado al carrito': 'Adicionado ao carrinho',
      'Pendiente por comprar': 'Pendente para comprar',
      'gastado hasta hoy': 'gasto até hoje',
      'Sueldo': 'Salário',
      'Freelance': 'Freelance',
      'Inversión': 'Investimento',
      'Regalo': 'Presente',
      'Venta': 'Venda',
      'Otro': 'Outro',
      'Comida': 'Comida',
      'Transporte': 'Transporte',
      'Compras': 'Compras',
      'Hogar': 'Casa',
      'Entretenimiento': 'Entretenimento',
      'Ahorro': 'Poupança',
      'Ahorro sin meta': 'Poupança sem meta',
      'Otros': 'Outros',
      'Aparta una cantidad sin asociarla a una meta.':
          'Separe um valor sem associá-lo a uma meta.',
      'Lista en curso': 'Lista em andamento',
      'No se pudieron cargar los movimientos:':
          'Não foi possível carregar as movimentações:',
      'Nueva contraseña': 'Nova senha',
      'Confirmar contraseña': 'Confirmar senha',
    },
  };

  static MovaLocalizations of(BuildContext context) =>
      Localizations.of<MovaLocalizations>(context, MovaLocalizations)!;
}

class _MovaLocalizationsDelegate
    extends LocalizationsDelegate<MovaLocalizations> {
  const _MovaLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['es', 'en', 'pt'].contains(locale.languageCode);

  @override
  Future<MovaLocalizations> load(Locale locale) async =>
      MovaLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<MovaLocalizations> old) =>
      false;
}

extension MovaLocalizationBuildContext on BuildContext {
  MovaLocalizations get l10n => MovaLocalizations.of(this);
}

String movaText(String source) =>
    MovaLocalizations(appLanguageController.language.locale).translate(source);
